server:
  port: 8001

#服务的名称
spring:
  application:
    name: zuul-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 606000

ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 3000
  eureka:
    enabled: true

#自定义路由映射
zuul:
  # 网关默认阻止将 cookie 传递给下游服务, 配置不过滤cookie
  sensitive-headers:
  routes:
    # 用户模块
    jesus-user:
      path: /auth/**
      serviceId: jesus-user
    #api 模块
    jesus-api:
      path: /back/**
      serviceId: jesus-api
    #前台项目地址 github
    github:
      path: /github
      serviceId: https://github.com/JesusChrist-ssr/jesus_managent
#  #统一入口为上面的配置，其他入口忽略
#  ignored-patterns: /jesus-*/**
#  #忽略整个服务，对外提供接口
#  ignored-services: order-service